AlolaIslandMelemele_hns_MapScripts::
	.byte 0


Test::
# 4 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	lock
# 5 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	msgbox Test_Text_0, MSGBOX_NPC
# 6 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	release
	end


Alola_Melemele_Mailbox::
# 11 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	lock
# 12 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	msgbox Alola_Melemele_Mailbox_Text_0
# 13 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	release
	end


Alola_Melemele_Melemele_Sign::
# 18 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	lock
# 19 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	msgbox Alola_Melemele_Melemele_Sign_Text_0
# 20 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	release
	end


Alola_Melemele_Pokecenter_Sign::
# 25 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	lock
# 26 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	msgbox Alola_Melemele_Pokecenter_Sign_Text_0
# 32 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	release
	end


Test_Text_0:
# 5 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	.string "hello testtest test!$"

Alola_Melemele_Mailbox_Text_0:
# 12 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	.string "Samson Oak's Villa$"

Alola_Melemele_Melemele_Sign_Text_0:
# 19 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	.string "Welcome to Melemele Island!$"

Alola_Melemele_Pokecenter_Sign_Text_0:
# 26 "data/maps/AlolaIslandMelemele_hns/scripts.pory"
	.string "Welcome to the Melemele Island\n"
	.string "Pokémon Center!\p"
	.string "This is the only Pokémon Center on the\n"
	.string "Alola Isles, so be sure to take care of\l"
	.string "your Pokémon while you're here!$"
