Melemele_House_3_hns_MapScripts::
	.byte 0


Melemele_House3_Woman::
# 4 "data/maps/Melemele_House_3_hns/scripts.pory"
	lock
# 5 "data/maps/Melemele_House_3_hns/scripts.pory"
	faceplayer
# 6 "data/maps/Melemele_House_3_hns/scripts.pory"
	msgbox Melemele_House3_Woman_Text_0, MSGBOX_AUTOCLOSE
# 10 "data/maps/Melemele_House_3_hns/scripts.pory"
	release
	end


Melemele_House3_Man::
# 15 "data/maps/Melemele_House_3_hns/scripts.pory"
	lock
# 16 "data/maps/Melemele_House_3_hns/scripts.pory"
	faceplayer
# 17 "data/maps/Melemele_House_3_hns/scripts.pory"
	msgbox Melemele_House3_Man_Text_0, MSGBOX_AUTOCLOSE
# 22 "data/maps/Melemele_House_3_hns/scripts.pory"
	release
	end


Melemele_House3_Woman_Text_0:
# 6 "data/maps/Melemele_House_3_hns/scripts.pory"
	.string "Island life here is so peaceful!\p"
	.string "And it's nice that my grandkids are just\n"
	.string "a quick boat ride away in Kanto!$"

Melemele_House3_Man_Text_0:
# 17 "data/maps/Melemele_House_3_hns/scripts.pory"
	.string "Dang tourists!\p"
	.string "My realtor said this place would be\n"
	.string "quiet… but I guess its cheaper to \l"
	.string "travel here than all the way to Alola.$"
