AlolaWater_hns_MapScripts::
	.byte 0


Alola_MelemeleSea_TrainerBattleSwimmer::
# 4 "data/maps/AlolaWater_hns/scripts.pory"
	trainerbattle_single TRAINER_MELEMELE_SWIMMER_2_HNS, Alola_MelemeleSea_TrainerBattleSwimmer_Text_0, Alola_MelemeleSea_TrainerBattleSwimmer_Text_1
# 5 "data/maps/AlolaWater_hns/scripts.pory"
	msgbox Alola_MelemeleSea_TrainerBattleSwimmer_Text_2, MSGBOX_AUTOCLOSE
# 7 "data/maps/AlolaWater_hns/scripts.pory"
	release
	end


Alola_MelemeleSea_TrainerBattleSwimmer_Text_0:
# 4 "data/maps/AlolaWater_hns/scripts.pory"
	.string "So much open water here!$"

Alola_MelemeleSea_TrainerBattleSwimmer_Text_1:
# 4 "data/maps/AlolaWater_hns/scripts.pory"
	.string "Ouch,\n pulled a hamstring…$"

Alola_MelemeleSea_TrainerBattleSwimmer_Text_2:
# 5 "data/maps/AlolaWater_hns/scripts.pory"
	.string "There are some strong currents here.\n"
	.string "I think it attracts strong Pokémon!$"
