Akala_House_hns_MapScripts::
	.byte 0


Alola_Akala_House_OldWoman::
# 4 "data/maps/Akala_House_hns/scripts.pory"
	lock
# 5 "data/maps/Akala_House_hns/scripts.pory"
	faceplayer
# 6 "data/maps/Akala_House_hns/scripts.pory"
	msgbox Alola_Akala_House_OldWoman_Text_0, MSGBOX_AUTOCLOSE
# 11 "data/maps/Akala_House_hns/scripts.pory"
	release
	end


Alola_Akala_House_OldWoman_Text_0:
# 6 "data/maps/Akala_House_hns/scripts.pory"
	.string "I tell my husband everyday not to feed\n"
	.string "the Pikipek, but he never listens!\p"
	.string "One day he'll bring one of those darn\n"
	.string "things home, I just know it!$"
